lukencode/FluentEmail

src/Renderers/FluentEmail.Razor/project.json, src/Renderers/FluentEmail.Razor/project.lock.json, test/FluentEmail.Razor.Tests/project.json, test/FluentEmail.Razor.Tests/project.lock.json
This resolves issue #44
I also bumped versions in the test project because it wouldn't run for me with the prerelease versions it had (I just have the final release of .NET Core 1.1 installed).
=> Fixing FluentEmail.Razor compatibility with .NET Framework

.gitignore, .vs/restore.dg, src/Senders/FluentEmail.SendGrid/SendGridSender.cs
Changed to copy the string as binary content and then converting to base64. Tested with XLSX attachment successfully.
I also removed the .vs folder from GIT since it's only used by VS to keep track of your settings, it shouldn't be committed.
=> Fix for #64

src/FluentEmail.Core/Defaults/SaveToDiskSender.cs, src/FluentEmail.Core/Interfaces/ISender.cs, src/Senders/FluentEmail.Mailgun/MailgunSender.cs, src/Senders/FluentEmail.SendGrid/SendGridSender.cs, src/Senders/FluentEmail.Smtp/SmtpSender.cs
Actually, we can't do :
```csharp
var email = Email.From(...).Subject(...).Body(...).To(...);
new SmtpSender().SendAsync(email);
```
because the type of the email variable is IFluentEmail while Email class is expected in ISender interface.
So, I replaced Email by IFluentEmail in ISender interface.
=> Uses IFluentEmail interface instead of Email class in ISender interface

src/Senders/FluentEmail.Smtp/SmtpSender.cs, test/FluentEmail.Smtp.Tests/FluentEmail.Smtp.Tests.csproj, test/FluentEmail.Smtp.Tests/SmtpSenderTests.cs
This is in response to problems listed in #46.  I did three things here:
1. Changed the SmtpSender to accept a method that returns an SmtpClient, this allows you to create & dispose of a new email you send.  It also lets you define the default sender in startup initialization code
2. I removed the UseSsl property in favor of configuring the SmtpClient directly.
3. I updated the unit test to save emails to a directory.  This lets you test without an SMTP server running.
I needed the first change for a project I was working on, thought I'd offer it to the upstream project in hopes of making it easier to work with :)
=> Changed FluentMail.Smtp to accept a method that returns an SmtpClient

src/Senders/FluentEmail.Mailgun/MailGunRegion.cs, src/Senders/FluentEmail.Mailgun/MailgunSender.cs
Added support for Mailgun's new EU region.
Constructor maintains existing signature if not using the region selector so backward compatible.
=> Added mailgun EU region support

sample/SampleWeb/Controllers/HomeController.cs, sample/SampleWeb/Models/ErrorViewModel.cs, sample/SampleWeb/Program.cs, sample/SampleWeb/Startup.cs, src/FluentEmail.Core/Defaults/ReplaceRenderer.cs, src/FluentEmail.Core/Defaults/SaveToDiskSender.cs, src/FluentEmail.Core/FluentEmailFactory.cs, src/FluentEmail.Core/FluentEmailServiceCollectionExtensions.cs, src/FluentEmail.Core/IFluentEmail.cs, src/FluentEmail.Core/Models/Attachment.cs, src/FluentEmail.Core/Models/SendResponse.cs, src/Renderers/FluentEmail.Razor/FluentEmailRazorBuilderExtensions.cs, src/Renderers/FluentEmail.Razor/InMemoryRazorLightProject.cs, src/Renderers/FluentEmail.Razor/RazorRenderer.cs, src/Senders/FluentEmail.Mailgun/FluentEmailMailgunBuilderExtensions.cs, src/Senders/FluentEmail.Mailgun/HttpHelpers/HttpClientHelpers.cs, src/Senders/FluentEmail.Mailgun/HttpHelpers/HttpFile.cs, src/Senders/FluentEmail.Mailgun/MailgunResponse.cs, src/Senders/FluentEmail.Mailgun/MailgunSender.cs, src/Senders/FluentEmail.SendGrid/FluentEmailSendGridBuilderExtensions.cs, src/Senders/FluentEmail.SendGrid/SendGridSender.cs, src/Senders/FluentEmail.Smtp/FluentEmailSmtpBuilderExtensions.cs, test/FluentEmail.Core.Tests/AttachmentTests.cs, test/FluentEmail.Core.Tests/TemplateEmailTests.cs, test/FluentEmail.Razor.Tests/RazorTests.cs, test/FluentEmail.SendGrid.Tests/SendGridSenderTests.cs, test/FluentEmail.Smtp.Tests/SmtpSenderTests.cs
Hey Luke, Some improvements, and a small bug fix.
the `SaveToDisk` used the wrong time formatter. using `yyy-MM-dd_hh-mm-ss` instead of `yyy-MM-dd_HH-mm-ss` means that sending one email at 4am and 4pm will both end up with "04" as hour.
It should be easiest to review per commit, since you'll have 3 simple small ones (as per commit message), and then a "big" commit which is only removing statements.
P.S.
There's an extra catchya hidden in the code though . You're using RazorLight alpha 3. 
Trying to send anything with a template from a .Net core 2.1+ explodes horribly and sadly.
As a workaround, you can use the simple replace engine.
Maybe worth writing something in the readme to save some unsuspecting users the puzzlement if they hit it? 
Cheers for your work.
=> Bug fix and some improvements.]

src/FluentEmail.Core/Defaults/SaveToDiskSender.cs, src/FluentEmail.Core/Email.cs, src/FluentEmail.Core/IFluentEmail.cs, src/FluentEmail.Core/Models/EmailData.cs, src/Senders/FluentEmail.Mailgun/MailgunSender.cs, src/Senders/FluentEmail.SendGrid/SendGridSender.cs, src/Senders/FluentEmail.Smtp/SmtpSender.cs, test/FluentEmail.Mailgun.Tests/MailgunSenderTests.cs
To use advanced features, like variables of mailgun. Custom Headers are really useful.
I have implemented now a way to add headers to a mail and also added it to the other mail senders.
For send grid and smtp I am not able to test it but it should work.
=> added functionality to add custom headers to mail

src/FluentEmail.Core/Models/Attachment.cs, src/Senders/FluentEmail.Smtp/SmtpSender.cs
For more info: https://stackoverflow.com/a/50564917/114029
This code made the image attachment show inline with SMTP and solves this issue:
https://github.com/lukencode/FluentEmail/issues/101
=> Added ContentID to SMTP to be able to inline image in the e-mail body.

src/FluentEmail.Core/Email.cs, src/FluentEmail.Core/IFluentEmail.cs, test/FluentEmail.Core.Tests/AttachmentTests.cs
Currently when using AttachFromFilename (at least in my use-case), the name of attachment will be the full path of the file which may or may not be desired.  This new parameter will allow the user to optionally specify the name of the attachment.
This is my first pull request and my first contribution to an open source project, so I'm totally open to feedback if something could be done better.
=> Added optional AttachmentName parameter to AttachFromFilename().

src/Senders/FluentEmail.Smtp/FluentEmailSmtpBuilderExtensions.cs
Quick and dirty, but also an effective way to get login support for the SMTP client. Tested working.
Before a nuget release someone could write tests and include login features it in the Core.Email object for non-DI users.
=> Adding SSL and login support for dependency injection extension method

src/Senders/FluentEmail.Smtp/FluentEmailSmtpBuilderExtensions.cs
Resolves "An asynchronous call is already in progress." error message due to SmtpClient being instantiated during startup and reused, irrespective of it being defined as a Scoped service.
Fixes #154
=> Fix AddSmtpSender extension methods to property add service

src/Senders/FluentEmail.MailKit/MailKitSender.cs
Hey @lukencode, I've tried to send a mail with the subject line "Vielen Dank für Ihre Registrierung". Without my modifications the MailKit did cause following headers:
Content-Id: <QCG39HVEDAU4.MDARRMP99QTJ3@localhost.localdomain>
Content-Type: text/html; charset=utf-8
Date: Tue, 14 Apr 2020 22:39:49 +0200
From: dev@somedomain.de
MIME-Version: 1.0
Message-Id: <OBYZCCVEDAU4.28XI177LT6OB@localhost.localdomain>
Received: from [127.0.0.1] by mailhog.example (MailHog)
id RQIVAZNd97u58c8I_8jOoVPamf-qeP64uDjyr9vCOe8=@mailhog.example; Tue, 14 Apr 2020 20:52:43 +0000
Return-Path: <dev@somedomain.de>
Subject: Vielen Dank =?iso-8859-1?b?Zvxy?= Ihre Registrierung
To: Stanley3@test.local
With my modifications it looks imho a bit better as as the content and subject are both encoded with UTF-8: …
=> Ensure the subject is utf-8 encoded

src/Senders/FluentEmail.MailKit/MailKitSender.cs
It’s needed for to be able to inline image in the e-mail body, as in the SmtpSender.
=> Add ContentId to the attachment at MailKitSender.

.github/workflows/dotnet-core.yml, test/FluentEmail.Core.Tests/AttachmentTests.cs, test/FluentEmail.Core.Tests/FluentEmail.Core.Tests.csproj, test/FluentEmail.Core.Tests/TemplateEmailTests.cs
I noticed there were a bunch of failing tests (11).  I found that the messages were complaining that the tests couldn't find a file (called test.txt).
I saw that the project did not include a copy always, so I have set the Copy Always flag for these files.  They were being copied, but I thought this more explicit.  
I digress - this was not the main issue.  The issue is that running these tests under a linux environment introduces File name case sensitivity.  These tests were referring to Test.txt, rather than test.txt.
I have corrected the case for these tests, and additionally constructed the path using path.combine - which will add the appropriate environment symbol for path separation.
=> Failing Tests (github actions)

src/FluentEmail.Core/Defaults/SaveToDiskSender.cs
Using `Path.Combine` instead of manually concatenating path with \
=> Fix SaveToDiskSender on non Windows environments

src/Senders/FluentEmail.MailKit/MailKitSender.cs, src/Senders/FluentEmail.MailKit/SmtpClientOptions.cs
This setting is needed, if you want to connect to the Office 365 SMTP service. The existing `UseSSL` flag does not work in this case.
```csharp
new SmtpClientOptions
{
Server = emailSettings.Host,
Port = emailSettings.Port,
User = emailSettings.Username,
Password = emailSettings.Password,
SocketOptions = SecureSocketOptions.StartTls,
RequiresAuthentication = true
};
```
=> Added ability to configure socket options while connecting via MailKit (e.g. for Office 365 SMTP service)

src/Senders/FluentEmail.SendGrid/FluentEmailSendGridBuilderExtensions.cs
I've got error with Scoped service lifetime with my .NET core application.
`Cannot resolve scoped service 'FluentEmail.Core.Interfaces.ISender' from root provider`
Changed to Singleton and tested with that and it worked. Also I was not able to send multiple emails, only one per application lifetime.
=> Sendgrid service lifetime now singleton

src/Renderers/FluentEmail.Razor/FluentEmail.Razor.csproj, src/Renderers/FluentEmail.Razor/RazorRenderer.cs
There were a couple of breaking changes on RazorLight ahead of beta1 version currently used by FluentEmail.
With this change, FluentEmail can now use the latest version of RazorLight.
=> Upgrading RazorLight to rc 3

src/FluentEmail.Core/ListExtensions.cs, src/FluentEmail.Core/Models/EmailData.cs, src/FluentEmail.Core/Models/SendResponse.cs, src/Senders/FluentEmail.Mailgun/HttpHelpers/ApiResponse.cs, src/Senders/FluentEmail.Mailgun/HttpHelpers/HttpClientHelpers.cs, src/Senders/FluentEmail.SendGrid/SendGridSender.cs
This makes the library a bit easier to use, as you don't have to convert your arrays to Lists to use functions taking an IList as a parameter. This naturally also applies to any other object implementing IList. I did the same for Dictionary, where I replaced parameters of type Dictionary with IEnumerable<KeyValuePair>, and properties of type Dictionary with IDictionary.
=> Replace consumption of List with IList, Dictionary with IEnumerable<KeyValuePair> or IDictionary

.github/workflows/publish-packages.yml, FluentEmail.sln, README.markdown, src/Directory.Build.props, src/FluentEmail.Core/FluentEmail.Core.csproj, src/Renderers/FluentEmail.Liquid/FluentEmail.Liquid.csproj, src/Renderers/FluentEmail.Liquid/FluentEmailFluidBuilderExtensions.cs, src/Renderers/FluentEmail.Liquid/FluidViewTemplate.cs, src/Renderers/FluentEmail.Liquid/LiquidRenderer.cs, src/Renderers/FluentEmail.Liquid/LiquidRendererOptions.cs, src/Renderers/FluentEmail.Liquid/Tags/LayoutTag.cs, src/Renderers/FluentEmail.Liquid/Tags/RegisterSectionBlock.cs, src/Renderers/FluentEmail.Liquid/Tags/RenderBodyTag.cs, src/Renderers/FluentEmail.Liquid/Tags/RenderSectionTag.cs, src/Renderers/FluentEmail.Razor/FluentEmail.Razor.csproj, test/FluentEmail.Liquid.Tests/EmailTemplates/_embedded.liquid, test/FluentEmail.Liquid.Tests/EmailTemplates/_layout.liquid, test/FluentEmail.Liquid.Tests/FluentEmail.Liquid.Tests.csproj, test/FluentEmail.Liquid.Tests/LiquidTests.cs
Secure alternative to Razor, supporting Shopify's templating language, [Liquid](https://shopify.github.io/liquid/). Liquid templates and sandboxed and cannot access the CLR the same way as Razor (think malicious file access).
* Simple and well supported templating language (plugins available for major IDEs and editors)
* Using [Fluid](https://github.com/sebastienros/fluid) as underlying engine
* Fast and secure, you can define what CLR access is allowed and recursion limits etc (unlike Razor)
* Used in projects like OrchardCMS
* Adapted master page support from Fluid MVC view engine support
@lukencode Please let me know if this is something you don't want to consider as part of the main project.
=> Add Liquid template language support

src/FluentEmail.Core/Email.cs, src/Senders/FluentEmail.SendGrid/SendGridSender.cs, test/FluentEmail.Core.Tests/SendGridSenderTests.cs
Implementation is using tags as those are similar concepts between mailgun and sendgrid.
Both have the same goal of tagging emails for statistics 
This fix #229
=> Fix #229 add support for sendgrid categories 

src/Senders/FluentEmail.Smtp/SmtpSender.cs, test/FluentEmail.Core.Tests/SmtpSenderTests.cs
This will fix this [issue](https://github.com/lukencode/FluentEmail/issues/264)
I've tried to create test for cancelling token during `SmtpClient.SendAsync` but there is no way to do it. These tests are using `SmtpClient` with storing emails on the disk (`SmtpDeliveryMethod.SpecifiedPickupDirectory`). I've looked at impelementation of `SmtpClient` and no found any solution to stop executing (saving email to disk) & call `token.Cancel()`.
=> fix SmtSender not passing CancellationToken to SmtpClient

src/Senders/FluentEmail.SendGrid/IFluentEmailExtensions.cs, src/Senders/FluentEmail.SendGrid/ISendGridSender.cs, src/Senders/FluentEmail.SendGrid/SendGridSender.cs, test/FluentEmail.Core.Tests/SendGridSenderTests.cs
This adds support for SendGrid's dynamic transactional templates (https://sendgrid.com/docs/ui/sending-email/how-to-send-an-email-with-dynamic-transactional-templates/).
This was done by adding a new interface for the `SendGridSender` (`ISendGridSender`), which inherits from `ISender`. Using the extension method `IFluentEmail.SendWithTemplateAsync`, you can now send messages using a transactional template. This is done by supplying the template ID and optional dynamic template data.
=> Add support for SendGrid dynamic templates.
