lukencode/FluentEmail

FluentEmail.Mailgun.Tests/FluentEmail.Mailgun.Tests.csproj, src/Senders/FluentEmail.SendGrid/FluentEmail.SendGrid.csproj, src/Senders/FluentEmail.SendGrid/SendGridSender.cs, test/FluentEmail.Core.Tests/FluentEmail.Core.Tests.csproj, test/FluentEmail.Razor.Tests/FluentEmail.Razor.Tests.csproj, test/FluentEmail.SendGrid.Tests/FluentEmail.SendGrid.Tests.csproj, test/FluentEmail.SendGrid.Tests/SendGridSenderTests.cs, test/FluentEmail.Smtp.Tests/FluentEmail.Smtp.Tests.csproj
Updated Sendgrid package to the latest.
Updates test suite to use latest packages. This also fixes the compatibility with NUnit 3 and VS2017.
=> Sendgrid updates

README.markdown
=> Updated usage readme

src/Senders/FluentEmail.Smtp/SmtpSender.cs
Added support for sending both HTML and plain text messages to SMTP Sender. Previously the AlternativePlainText was ignored.
=> Added support for sending both HTML and plain text messages to SMTP Sender

src/FluentEmail.Core/Email.cs, src/FluentEmail.Core/IFluentEmail.cs, test/FluentEmail.Core.Tests/AddressTests.cs
Method used to change the send from address when using an injected instance of IFluentEmail.
fixes #96
=> Added at SetFrom method to IFluentEmail

src/Senders/FluentEmail.Mailgun/MailgunSender.cs
=> Updated mailgunsender to implement Reply-To

src/Senders/FluentEmail.Smtp/SmtpSender.cs
Sometimes, we want to pass an SmtpClient to the SmtpSender class but we want to keep it alive, it should not be disposed by the Send method.
So, I added a the constructor SmtpSender(SmtpClient smtpClient) to have the both cases.
=> Adds the possibility to pass your own SmtpClient without disposing it

src/FluentEmail.Core/Email.cs, src/FluentEmail.Core/IFluentEmail.cs, src/FluentEmail.Core/Models/EmailData.cs, src/Senders/FluentEmail.Mailgun/MailgunSender.cs, test/FluentEmail.Mailgun.Tests/FluentEmail.Mailgun.Tests.csproj, test/FluentEmail.Mailgun.Tests/MailgunSenderTests.cs
Hey
I added support for tagging (currently only for mailgun). Also updated the nugets in the test project. Looking forward for a new nuget release.
Cheers
=> added tag support for mailgun

src/Renderers/FluentEmail.Razor/FluentEmail.Razor.csproj
This allows users to build and run a .net framework console app using dotnet
=> Fixing issue for dotnet framework users unable to run project

src/Senders/FluentEmail.SendGrid/Changelog.md, src/Senders/FluentEmail.SendGrid/FluentEmail.SendGrid.csproj, src/Senders/FluentEmail.SendGrid/SendGridSender.cs
Fix issue #129 by updating sendgrid dependancy and code.
=> Update Sendgrid dependancy

src/FluentEmail.Core/Models/SendResponse.cs, src/Senders/FluentEmail.Mailgun/MailgunSender.cs, test/FluentEmail.Mailgun.Tests/MailgunSenderTests.cs
This would allow tracking of a mail message.
https://www.mailgun.com/blog/tracking-replies-in-mailgun-or-any-other-email
=> added message id to sendresponse

src/Senders/FluentEmail.Mailgun/MailgunSender.cs
=> Fix null exception when mailgun return an error

README.markdown
=> Fix SendGrid link

src/Senders/FluentEmail.SendGrid/SendGridSender.cs
Correctly returns MessageId from SendGridResponse.
=> Set MessageId in SendGridSender

src/FluentEmail.Core/Models/Address.cs, src/Senders/FluentEmail.MailKit/MailKitSender.cs
Fixed up some missing references and methods.
=> Code cleanup

src/FluentEmail.Core/FluentEmail.Core.csproj, src/Renderers/FluentEmail.Razor/FluentEmail.Razor.csproj, src/Senders/FluentEmail.MailKit/FluentEmail.MailKit.csproj, src/Senders/FluentEmail.Mailgun/FluentEmail.Mailgun.csproj, src/Senders/FluentEmail.SendGrid/FluentEmail.SendGrid.csproj, test/FluentEmail.Core.Tests/FluentEmail.Core.Tests.csproj, test/FluentEmail.MailKit.Tests/FluentEmail.MailKit.Tests.csproj, test/FluentEmail.Mailgun.Tests/FluentEmail.Mailgun.Tests.csproj, test/FluentEmail.Mailtrap.Tests/FluentEmail.Mailtrap.Tests.csproj, test/FluentEmail.Mailtrap.Tests/MailtrapSenderTests.cs, test/FluentEmail.Razor.Tests/FluentEmail.Razor.Tests.csproj, test/FluentEmail.SendGrid.Tests/FluentEmail.SendGrid.Tests.csproj, test/FluentEmail.SendGrid.Tests/SendGridSenderTests.cs, test/FluentEmail.Smtp.Tests/FluentEmail.Smtp.Tests.csproj
- Updated nuget packages
- Ignore tests that require credentials
=> Updated out of date packages

src/Senders/FluentEmail.SendGrid/SendGridSender.cs, test/FluentEmail.SendGrid.Tests/SendGridSenderTests.cs
Please note that SendGrid does not support multiple ReplyTo addresses
=> Added support for SendGrid ReplyTo

FluentEmail.Graph.Tests/FluentEmail.Graph.Tests.csproj, FluentEmail.Graph.Tests/GraphSenderTests.cs, FluentEmail.Graph/FluentEmail.Graph.csproj, FluentEmail.Graph/FluentEmail.Graph.vbproj, FluentEmail.Graph/FluentEmailGraphBuilderExtensions.cs, FluentEmail.Graph/GraphSender.cs, FluentEmail.sln
This PR adds a Microsoft Graph sender, enabling users to send email using their Office 365 tenant
=> Add Graph Sender

.github/workflows/publish-packages.yml, src/Directory.Build.props, src/FluentEmail.Core/FluentEmail.Core.csproj, src/Renderers/FluentEmail.Razor/FluentEmail.Razor.csproj, src/Senders/FluentEmail.Graph/FluentEmail.Graph.csproj, src/Senders/FluentEmail.MailKit/FluentEmail.MailKit.csproj, src/Senders/FluentEmail.Mailgun/FluentEmail.Mailgun.csproj, src/Senders/FluentEmail.Mailtrap/FluentEmail.Mailtrap.csproj, src/Senders/FluentEmail.SendGrid/FluentEmail.SendGrid.csproj, src/Senders/FluentEmail.Smtp/FluentEmail.Smtp.csproj
Merged some outstanding PRs and bumped the versions so that nuget packages are created.
I believe the <version> is required for the publish action.
=> Re-added and bumped version tags for projects

src/Senders/FluentEmail.MailKit/MailKitSender.cs
This pull request prevents the duplication of the subject headers in MailKit
=>  Prevents Duplicate Subject Header in MailKit

src/Renderers/FluentEmail.Liquid/FluentEmail.Liquid.csproj
It would be nice to get attribution by adding my name to NuGet package authors.
=> Update FluentEmail.Liquid.csproj Authors
